### ISSUE TITLE
[normalization] File location

### ISSUE THREAD

**Issue by jcheron** [Lapinskas/roadrunner-ubiquity#13]
To respect the directory structure of an Ubiquity project:
- The file `worker.php` should be in the `.ubiquity` folder of the project (as for other servers: php-pm, Swoole, Workerman, PHP...)
Its name is ambiguous (**worker** could refer to Workerman...). I would rather choose **rrIndex.php**

- The configuration file `.rr.yml` should be in the `app/config` folder (or in `.ubiquity`).

**Comment by Lapinskas** [comment]
Thank you for the suggestion!

We have renamed `worker.php` to `rr-worker.php` and placed it to `.ubiquity` folder

`.rr.yml` as well placed to `.ubiquity` folder, however its symlinked from the root folder for convenience.
