### ISSUE TITLE
Wrong header parser on response. Location header missing

### ISSUE THREAD

**Issue by soceans02** [Lapinskas/roadrunner-ubiquity#26]
In https://github.com/Lapinskas/roadrunner-ubiquity/blob/f8b0946167834bb73b163121bc5ddc0dd6f0ac79/src/Request.php#L93 split function using ":" separator makes some headers incomplete, e.g.: "Location" header

```php
    header('Location: http://www.example.com/');

```
After request header parsing becomes:

"Location: http"

**Comment by Lapinskas** [comment]
Hello @soceans02,

Nice catch, thank you! I have fixed the issue in the latest release.
